# Uses the dependency-graph/sboms REST API to aquire an SPDX SBOM, attest with build provenance, and upload as an artifact.
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
name: Generate SBOM
permissions:
  id-token: write
  contents: read
  attestations: write
jobs:
  gen-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Calls the REST API: https://docs.github.com/en/rest/dependency-graph/sboms?apiVersion=2022-11-28
    - uses: advanced-security/generate-sbom-action@v1
      id: gensbom
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:          
        subject-path: ${{ steps.gensbom.outputs.fileName }}
    - uses: actions/upload-artifact@v4
      with:
        name: sbom-spdx
        path: ${{ steps.gensbom.outputs.fileName }}
    - name: Download CycloneDX CLI
      run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/CycloneDX/cyclonedx-cli/releases/latest | jq -r '.tag_name')
          curl -Lo cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/download/${LATEST_RELEASE}/cyclonedx-linux-x64
          chmod +x cyclonedx          
          
    - name: Convert SPDX SBOM to CycloneDX
      run: |
          ./cyclonedx convert --input-file ${{ steps.gensbom.outputs.fileName }} --output-file sbom.cyclonedx.json --input-format spdxjson --output-format json

    - uses: actions/upload-artifact@v4
      with:
        name: sbom-cyclonedx
        path: sbom.cyclonedx.json
